# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js
on:
   push:
     branches: [ "master" ]
   pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 15
    - name: Excute
      run: |
        git clone https://github.com/github-host2/steam.git
        cd steam
        npm install discord-interactions
        npm install dotenv
    - name: Setup Bot
      run: |
        cd steam
        npm install
        npm run start
